apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cassandra-operator
  name: cassandra-webhook
  namespace: "$TARGET_NAMESPACE"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-operator
      deployment: cassandra-webhook
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra-operator
        deployment: cassandra-webhook
    spec:
      containers:
      - image: $WEBHOOK_IMAGE
        imagePullPolicy: IfNotPresent
        name: webhook
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: "0"
            memory: 50Mi
        volumeMounts:
        - name: serving-certs
          mountPath: "/tmp/k8s-webhook-server/serving-certs"
          readOnly: true
      volumes:
      - name: serving-certs
        secret:
          secretName: cassandra-operator-webhook-tls
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: "$TARGET_NAMESPACE"
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: cassandra-operator
    deployment: cassandra-webhook
  type: ClusterIP
