apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cassandra-operator-webhook
  name: cassandra-operator-webhook
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-operator-webhook
      deployment: cassandra-operator-webhook
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra-operator-webhook
        deployment: cassandra-operator-webhook
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: APP_NAME
          value: cassandra-operator-webhook
        args:
        - --v=2
        - --secure-port=6443
        - --tls-cert-file=/certs/tls.crt
        - --tls-private-key-file=/certs/tls.key
        image: $IMAGE
        imagePullPolicy: IfNotPresent
        name: cassandra-operator-webhook
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: "0"
            memory: 256Mi
        volumeMounts:
        - name: certs
          mountPath: /certs
      volumes:
      - name: certs
        secret:
          secretName: cassandra-operator-webhook-tls
      restartPolicy: Always
      serviceAccount: cassandra-operator-webhook
      serviceAccountName: cassandra-operator-webhook
      terminationGracePeriodSeconds: 30
