apiVersion: v1
kind: ServiceAccount
metadata:
  name: cassandra-webhook
  namespace: $TARGET_NAMESPACE
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cassandra-webhook
  name: cassandra-webhook
  namespace: $TARGET_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-webhook
      deployment: cassandra-webhook
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra-webhook
        deployment: cassandra-webhook
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: APP_NAME
          value: cassandra-webhook
        args: $ARGS
        image: $IMAGE
        imagePullPolicy: IfNotPresent
        name: cassandra-webhook
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: "0"
            memory: 256Mi
      restartPolicy: Always
      serviceAccount: cassandra-webhook
      serviceAccountName: cassandra-webhook
      terminationGracePeriodSeconds: 30
